import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from './theme-provider'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en" className='h-full'>
      <body className={cn("relative h-full antialiased", inter.className)}>
        <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
          <Providers>
            <main className="relative flex flex-col min-h-screen">
              <Navbar />
              <div className="flex-1 flex-grow">
                {children}
              </div>
              <Toaster position='top-right' richColors theme='system' />
            </main>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
